### ISSUE TITLE
Just WOW!

### ISSUE THREAD

**Issue by PySimpleGUI** [vfsousas/spytool#1]
![image](https://user-images.githubusercontent.com/46163555/149406436-a6946923-3a4a-4fdb-ab03-0b31da314741.png)

This is such a cool program!

It reminds me a little of WinSpy++

![image](https://user-images.githubusercontent.com/46163555/149405979-202b0493-f0de-4a91-83d7-d4bbbba92efa.png)

I'm having fun watching it simply draw boxes on the windows.  It's fascinating to watch.

I've got a very large monitor and keep a large number of PySimpleGUI programming running so I made your sizes larger and made the window resizable:

![image](https://user-images.githubusercontent.com/46163555/149406263-facdc885-4b3f-4207-9c8a-2e84c575afa2.png)

Here's how your program analyzed one of my weather desktop widgets:

![image](https://user-images.githubusercontent.com/46163555/149406375-5b1b3620-f218-444c-98d2-e925f9ee27fe.png)

Thank you for posting a screenshot in your readme.  It grabbed my attention.

**Comment by PySimpleGUI** [comment]
ShareX makes GIFs that are small enough to fit into a readme if you're interested in maybe embedding a GIF into your readme.  I saw your MP4, but I was unable to convert it into a GIF.  This one I made on my system and it's only 156K.

![ScreenCaptureUsingShareX](https://user-images.githubusercontent.com/46163555/149410841-6e1aad01-6b7c-4737-b31e-d80a9f95bb59.gif)

**Comment by vfsousas** [comment]
Thank you so much for comments @PySimpleGUI 
You work are awesome, with PySimpleGUI I was able to delivery this little project to my team in less than one week.
You made my job very, very easy since draw UI using Python until today is a little bit complex.

More features in SpyTool will come soon.

Thanks for the GIF animation, I´ll include in readme now..
